import { Router } from "express";
import authRoutes from "../modules/auth/auth.routes";
import userRoutes from "../modules/user/user.routes";
import blogRoutes from "../modules/blog/blog.routes";
import galleryRoutes from "../modules/gallery/gallery.routes";
import testimonialRoutes from "../modules/testimonial/testimonial.routes";
import enquiryRoutes from "../modules/enquiry/enquiry.routes";
import faqRoutes from "../modules/faq/faq.routes";
import settingRoutes from "../modules/setting/setting.routes";
import uploadRoutes from "../modules/upload/upload.routes";
import donationRoutes from "../modules/donation/donation.routes";
import requestRoutes from "../modules/request/request.routes";
import caseRoutes from "../modules/case/case.routes";
import volunteerRoutes from "../modules/volunteer/volunteer.routes";
import campaignRoutes from "../modules/campaign/campaign.routes";
import reportRoutes from "../modules/report/report.routes";
import vehicleRoutes from "../modules/vehicle/vehicle.routes";
import serviceProviderRoutes from "../modules/serviceProvider/serviceProvider.routes";
import expenseCategoryRoutes from "../modules/expenseCategory/expenseCategory.routes";
import partnerRoutes from "../modules/partner/partner.routes";
import roleRoutes from "../modules/role/role.routes";
import auditRoutes from "../modules/audit/audit.routes";
import newsletterRoutes from "../modules/newsletter/newsletter.routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/blog", blogRoutes);
router.use("/gallery", galleryRoutes);
router.use("/testimonials", testimonialRoutes);
router.use("/enquiries", enquiryRoutes);
router.use("/faqs", faqRoutes);
router.use("/settings", settingRoutes);
router.use("/uploads", uploadRoutes);
router.use("/donations", donationRoutes);
router.use("/requests", requestRoutes);
router.use("/cases", caseRoutes);
router.use("/volunteers", volunteerRoutes);
router.use("/campaigns", campaignRoutes);
router.use("/reports", reportRoutes);
router.use("/vehicles", vehicleRoutes);
router.use("/service-providers", serviceProviderRoutes);
router.use("/expense-categories", expenseCategoryRoutes);
router.use("/partners", partnerRoutes);
router.use("/roles", roleRoutes);
router.use("/audit", auditRoutes);
router.use("/newsletter", newsletterRoutes);

export default router;
